# Setup
title:    Taller Programación 1
tagline:  Introdución a la Programación I - Taller
baseurl:  /tallerprog1
zip:	    https://github.com/FacultadDeIngenieria/tallerprog1/zipball/gh-pages

# About/contact
author:
name:       Introdución a la Programación I - Taller
